apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo-app-deployment
  labels:
    app: docker-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-demo-app
  template:
    metadata:
      labels:
        app: docker-demo-app
    spec:
      containers:
        - name: docker-demo-cont
          image: frostfrost/dockerfirstapp:docker-demo-service
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5